name: go-docker
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - run: go mod init go mod tidy go test
      - uses: actions/checkout@v2
      - name: Run Unit Tests
