name: go-docker
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Go Mod Tidy
        run: go mod tidy
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test
